### PR TITLE
Add support for Sphinx documentation

### LINKED ISSUE #7: API Reference Documentation
Sphinx is a powerful and flexible tool specifically designed for documenting Python projects, and it works very well for generating API references. It can automatically generate documentation from docstrings in the code.

We can create a `docs/` folder for hosting the API documentation.

### PR DESCRIPTION
**Pull request by theiiienrique**
Closes #7 

Related to #6

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @theiiienrique, thank you for opening the PR.
Let's get the status checks failure resolved first.

You need to rebase the commits, squash them into one and add the missing sign off

Add https://github.com/5-jigglypuff/pytrello2 as upstream
```bash
git remote add upstream https://github.com/5-jigglypuff/pytrello2
```

Rebase the latest changes
```bash
git fetch upstream
git rebase upstream/master
```

Squash all your commits into one
Assuming you will have your 8 commits sorted
```bash
git reset --soft HEAD~8
git commit -s -m "docs: add Sphinx documentation"
git push origin master -f
```

You should be all set here. Let me know if you need any help.

**Comment by theiiienrique** [comment]
Hi @vchrombie, thanks very much for your help. Let me know if any errors persist and if I can help fix them in any way.

**Comment by vchrombie** [comment]
Hi @theiiienrique, thank you so much for your contribution.

I changed a few things about how the documentation will be generated. Since we have some content already (README.md), I utilized it. I also updated your github action workflow to generate the api reference instead of updating it regularly.

What do you think about the PR?

**Comment by theiiienrique** [comment]
Hi @vchrombie, I think this looks good! Thanks so much for your revisions and for helping me with this.

**Comment by vchrombie** [comment]
I appreciate your efforts to get this feature started. Thank you so much @theiiienrique!

**Comment by vchrombie** [comment]
Could you review this PR when you get time? @jessat

**Review by jessat — APPROVED** [review]

**Comment by jessat** [comment]
Approved and merged.

**Pull request merged**
